/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.Vista;

import Servidor.GameEvent;
import Cliente.Observable.Observer;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author img
 */
public class VentanaPuntuacion extends JFrame implements Observer {
    
    private int idVentana;
    private int puntuacion;
    private String nombreCliente;

    public VentanaPuntuacion(int idVentana) {
           initComponents();
           this.idVentana = idVentana;
           this.puntuacion = 1;
           this.nombreCliente = "";
           this.puntuacionTextField.setEnabled(true);
           this.puntuacionTextField.setEditable(true);
           this.puntuacionTextField.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        puntuacionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        puntuacionTextField.setText("jTextField1");
        puntuacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntuacionTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Puntuación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(puntuacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(puntuacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puntuacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntuacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntuacionTextFieldActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField puntuacionTextField;
    // End of variables declaration//GEN-END:variables

    //@Override
    public void notifyEvent(GameEvent evento) {
        
        SwingUtilities.invokeLater(new Runnable() {
            //SwingUtilities clase que contiene el metodod static 'invokeLater'
            //Runnable: interfaz que solo tiene el método run
            // el objetivo de lo anterior es crear una cola de eventos para ir almacenando los eventos
            @Override
            public void run() {
                manejarEvento(evento);
            } 
        });
    }
    
    
    
    public void manejarEvento (GameEvent evento) {
        switch (evento.getEvento()){
            
            case START:
                if(this.idVentana == (int)evento.getDatos6()){
                    this.nombreCliente = (String)evento.getDatos4();
                    iniciarMarcador();
                }
                    break; 
            
            case NUEVA_FRUTA: 
                if(this.idVentana == (int)evento.getDatos2()){
                    this.puntuacion = this.puntuacion +1;
                    mostrarPuntuacion(this.puntuacion);
                }
                    break;
                    
            case REINICIAR: 
                    reiniciarMarcador();
                    break; 
        }
    }
    
    private void mostrarPuntuacion(int puntuacion) {
        puntuacionTextField.setText("         " + puntuacion);
    }

    private void reiniciarMarcador() {
        this.jLabel1.setText("Puntuación");
        puntuacionTextField.setText("         1");
    }

    private void iniciarMarcador() {
        this.jLabel1.setText(this.nombreCliente);
        puntuacionTextField.setText("         1");
    }
}
