/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.Vista;

import Servidor.GameEvent;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author img
 */
public class VentanaPuntuacion extends JFrame {
    
    private int idVentana;
    private int puntuacion;
    private String nombreCliente;

    public VentanaPuntuacion() {
           initComponents();
           this.puntuacion = 1;
           this.nombreCliente = "";
           this.puntuacionTextField.setEnabled(true);
           this.puntuacionTextField.setEditable(true);
           this.puntuacionTextField.setText("");

    }
    
    /* 
        Como Observable es clase y no interfaz (y las ventanas
        ya extienden de la clase JFrame), hay que usar una forma
        alternativa de notificar eventos. Creamos una clase 
        observable como atributo de la ventana y mandamos las
        notificaciones a través de esta.
    */
    
    private static class MyObservable extends Observable {
        @Override
        public void setChanged() {
            super.setChanged();
        }
    }
    private final MyObservable observable = new MyObservable();
    
    public Observable getObservable() { return this.observable; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        puntuacionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        puntuacionTextField.setText("jTextField1");
        puntuacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntuacionTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Puntuación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(puntuacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(puntuacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puntuacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntuacionTextFieldActionPerformed
        // No queremos de momento que haga nada
    }//GEN-LAST:event_puntuacionTextFieldActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField puntuacionTextField;
    // End of variables declaration//GEN-END:variables

    
    private void mostrarPuntuacion(int puntuacion) {
        puntuacionTextField.setText("         " + puntuacion);
    }

    private void iniciarMarcador() {
        this.jLabel1.setText(this.nombreCliente);
        puntuacionTextField.setText("         1");
    }
    
    // MÉTODOS QUE USA EL CONTROLADOR
    
    public void setIdVentana(int id) {
        this.idVentana = id;
    }
    
    public void actualizarPuntuacion(int jugPuntos, int puntuacion) {
        if (this.idVentana == jugPuntos) {
            this.puntuacion = puntuacion;
            mostrarPuntuacion(this.puntuacion);
        }
    }
    
    public void reiniciarMarcador() {
        this.jLabel1.setText("Puntuación");
        puntuacionTextField.setText("         1");
    }
    
    public void setNombre(String nombre) {
        this.nombreCliente = nombre;
        this.jLabel1.setText(this.nombreCliente);
    }
    
    // Esta ventana de momento no le envía información al controlador
    
    
}
